name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: none
          extensions: swoole-6.2.0
          ini-values: assert.exception=1, zend.assertions=1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-version }}-composer-
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --prefer-dist --no-plugins

      - name: Run test suite
        run: ./vendor/bin/phpunit
